table dURL_Demanda
	lineageTag: 81a3ddda-ef7b-4192-96a9-d89321296e83

	column 'Demanda #'
		dataType: string
		lineageTag: cd2df224-ec60-437c-aec6-bd1409b6ae03
		summarizeBy: none
		sourceColumn: Demanda #

		annotation SummarizationSetBy = Automatic

	column Sys_id
		dataType: string
		lineageTag: 6b5c35fe-366e-46df-8029-92db0a68d011
		summarizeBy: none
		sourceColumn: Sys_id

		annotation SummarizationSetBy = Automatic

	column 'URL Demanda'
		dataType: string
		lineageTag: 7d5b1a29-74f6-47b1-842a-ec206a8a2ff9
		dataCategory: WebUrl
		summarizeBy: none
		sourceColumn: URL Demanda

		annotation SummarizationSetBy = Automatic

	partition dURL_Demanda = m
		mode: import
		queryGroup: Main
		source =
				let
				    Fonte = Json.Document(Web.Contents("https://arcelormittal.sharepoint.com/sites/CDM-CMT/Shared%20Documents/CMT/00%20-%20Atua%C3%A7%C3%A3o%20CMT/03.%20PBI/URL_Demanda.json")),
				    #"Convertido para Tabela" = Table.FromRecords({Fonte}),
				    #"records Expandido" = Table.ExpandListColumn(#"Convertido para Tabela", "records"),
				    #"records Expandido1" = Table.ExpandRecordColumn(#"records Expandido", "records", {"parent", "close_demand", "u_num_sipep", "watch_list", "other_costs", "u_annual_cash_flow_gain", "u_one_time_earning", "sys_updated_on", "u_annual_fixed_cost_gain", "skills", "score", "u_total_fte_own", "u_cancellation_reason", "related_records", "u_downgrade_reason_l1", "labor_costs", "u_downgrade_reason_l2", "u_downgrade_reason_l3", "u_participants_emails", "state", "u_downgrade_reason_l4", "sys_created_by", "expected_roi", "goals", "knowledge", "u_downgrade_reason_l0", "financial_benefit_demand_currency", "u_risk_description", "impact", "u_training_need", "active", "demand", "net_present_value_demand_currency", "u_kmm_stage", "u_vice_presidency", "investment_type", "group_list", "size", "u_benefits", "u_board_of_directors", "financial_return", "total_costs", "score_risk", "u_user_leader", "u_weekly_progress", "correlation_display", "u_kpi_detailing", "service_offering", "follow_up", "in_scope", "u_restrictive_factors", "u_approval_needed", "u_environmental_risk", "u_implementation_assumptions", "business_applications", "u_support_required", "u_facility_downtime_risk", "u_cancellation_date", "u_user_leader_history", "comments_and_work_notes", "resource_allocated_cost", "risk_of_performing", "u_cancellation_user", "stage", "escalation", "demand_actual_cost", "correlation_id", "u_ease_of_implementation", "u_phase", "made_sla", "scrum_story", "u_one_time_detail", "project", "strategic_objectives", "enhancement", "u_date_l4_original", "capital_budget", "user_input", "sys_created_on", "expected_risk", "route_reason", "closed_at", "time_worked", "u_demand_stage", "npv_value", "work_end", "u_date_l5_original", "work_notes", "u_need_for_detailed_risk_analysis", "u_department", "u_next_steps", "assignment_group", "u_involved_areas", "idea", "description", "capital_expense_demand_currency", "risk_of_not_performing", "sys_id", "u_number_value_plan", "urgency", "company", "rate_model", "u_current_status", "u_color_status", "approved_start_date", "u_digital_transformation_check", "enablers", "approval", "model_id", "improvement", "sys_tags", "u_total_fte_third", "u_downgrade_user_l4", "u_downgrade_user_l0", "u_downgrade_user_l1", "location", "u_downgrade_user_l2", "assessment_required", "u_downgrade_user_l3", "u_need_for_economic_feasibility", "project_currency", "upon_reject", "type", "discount_rate", "approval_history", "number", "defect", "u_occupational_safety_risk", "financial_return_demand_currency", "u_area", "collaborators", "order", "__status", "goal", "cmdb_ci", "contract", "work_notes_list", "priority", "sys_domain_path", "business_unit", "u_next_phase_date", "business_duration", "requested_by", "u_main_results", "score_value", "score_cost", "universal_request", "business_capabilities", "total_planned_cost_demand_currency", "short_description", "operating_expense_demand_currency", "work_start", "actual_cost_demand_currency", "u_annual_revenue_gain", "additional_assignee_list", "sys_class_name", "closed_by", "calculation_type", "capital_budget_demand_currency", "score_strategic_allignment", "u_annual_fixed_avoided_cost", "u_main_technology_associated", "u_last_status_update", "operational_budget", "reassignment_count", "assigned_to", "start_date", "demand_actual_effort", "u_net_gain_value", "u_annual_variable_cost_gain", "sla_due", "change", "demand_currency", "upon_approval", "u_annual_variable_avoided_cost", "impacted_business_units", "financial_benefit", "u_fte_check", "submitted_date", "u_division", "operating_budget_demand_currency", "u_confidential", "out_of_scope", "assumptions", "task_effective_number", "u_previous_state", "sys_updated_by", "opened_by", "portfolio", "u_reducao_co2", "sys_domain", "project_manager", "operational_outlay", "investment_class", "resource_planned_cost", "expense_type", "business_service", "expected_start", "visited_state", "opened_at", "primary_program", "scrum_epic", "irr_value", "u_user_leader_principal", "submitter", "u_report_date_l5", "u_report_date_l4", "software_model", "u_hours_month_of_efficiency", "business_case", "calendar_duration", "u_report_date_l3", "u_report_date_l2", "close_notes", "u_report_date_l1", "u_report_date_l0", "contact_type", "u_spend_detail", "u_pmo", "department", "activity_due", "approved_end_date", "u_product_quality_risk", "u_cancellation_type", "comments", "u_date_l3_original", "capital_outlay", "due_date", "sys_mod_count", "score_size", "u_total_fte", "barriers", "demand_manager", "category", "u_total_gains"}, {"records.parent", "records.close_demand", "records.u_num_sipep", "records.watch_list", "records.other_costs", "records.u_annual_cash_flow_gain", "records.u_one_time_earning", "records.sys_updated_on", "records.u_annual_fixed_cost_gain", "records.skills", "records.score", "records.u_total_fte_own", "records.u_cancellation_reason", "records.related_records", "records.u_downgrade_reason_l1", "records.labor_costs", "records.u_downgrade_reason_l2", "records.u_downgrade_reason_l3", "records.u_participants_emails", "records.state", "records.u_downgrade_reason_l4", "records.sys_created_by", "records.expected_roi", "records.goals", "records.knowledge", "records.u_downgrade_reason_l0", "records.financial_benefit_demand_currency", "records.u_risk_description", "records.impact", "records.u_training_need", "records.active", "records.demand", "records.net_present_value_demand_currency", "records.u_kmm_stage", "records.u_vice_presidency", "records.investment_type", "records.group_list", "records.size", "records.u_benefits", "records.u_board_of_directors", "records.financial_return", "records.total_costs", "records.score_risk", "records.u_user_leader", "records.u_weekly_progress", "records.correlation_display", "records.u_kpi_detailing", "records.service_offering", "records.follow_up", "records.in_scope", "records.u_restrictive_factors", "records.u_approval_needed", "records.u_environmental_risk", "records.u_implementation_assumptions", "records.business_applications", "records.u_support_required", "records.u_facility_downtime_risk", "records.u_cancellation_date", "records.u_user_leader_history", "records.comments_and_work_notes", "records.resource_allocated_cost", "records.risk_of_performing", "records.u_cancellation_user", "records.stage", "records.escalation", "records.demand_actual_cost", "records.correlation_id", "records.u_ease_of_implementation", "records.u_phase", "records.made_sla", "records.scrum_story", "records.u_one_time_detail", "records.project", "records.strategic_objectives", "records.enhancement", "records.u_date_l4_original", "records.capital_budget", "records.user_input", "records.sys_created_on", "records.expected_risk", "records.route_reason", "records.closed_at", "records.time_worked", "records.u_demand_stage", "records.npv_value", "records.work_end", "records.u_date_l5_original", "records.work_notes", "records.u_need_for_detailed_risk_analysis", "records.u_department", "records.u_next_steps", "records.assignment_group", "records.u_involved_areas", "records.idea", "records.description", "records.capital_expense_demand_currency", "records.risk_of_not_performing", "records.sys_id", "records.u_number_value_plan", "records.urgency", "records.company", "records.rate_model", "records.u_current_status", "records.u_color_status", "records.approved_start_date", "records.u_digital_transformation_check", "records.enablers", "records.approval", "records.model_id", "records.improvement", "records.sys_tags", "records.u_total_fte_third", "records.u_downgrade_user_l4", "records.u_downgrade_user_l0", "records.u_downgrade_user_l1", "records.location", "records.u_downgrade_user_l2", "records.assessment_required", "records.u_downgrade_user_l3", "records.u_need_for_economic_feasibility", "records.project_currency", "records.upon_reject", "records.type", "records.discount_rate", "records.approval_history", "records.number", "records.defect", "records.u_occupational_safety_risk", "records.financial_return_demand_currency", "records.u_area", "records.collaborators", "records.order", "records.__status", "records.goal", "records.cmdb_ci", "records.contract", "records.work_notes_list", "records.priority", "records.sys_domain_path", "records.business_unit", "records.u_next_phase_date", "records.business_duration", "records.requested_by", "records.u_main_results", "records.score_value", "records.score_cost", "records.universal_request", "records.business_capabilities", "records.total_planned_cost_demand_currency", "records.short_description", "records.operating_expense_demand_currency", "records.work_start", "records.actual_cost_demand_currency", "records.u_annual_revenue_gain", "records.additional_assignee_list", "records.sys_class_name", "records.closed_by", "records.calculation_type", "records.capital_budget_demand_currency", "records.score_strategic_allignment", "records.u_annual_fixed_avoided_cost", "records.u_main_technology_associated", "records.u_last_status_update", "records.operational_budget", "records.reassignment_count", "records.assigned_to", "records.start_date", "records.demand_actual_effort", "records.u_net_gain_value", "records.u_annual_variable_cost_gain", "records.sla_due", "records.change", "records.demand_currency", "records.upon_approval", "records.u_annual_variable_avoided_cost", "records.impacted_business_units", "records.financial_benefit", "records.u_fte_check", "records.submitted_date", "records.u_division", "records.operating_budget_demand_currency", "records.u_confidential", "records.out_of_scope", "records.assumptions", "records.task_effective_number", "records.u_previous_state", "records.sys_updated_by", "records.opened_by", "records.portfolio", "records.u_reducao_co2", "records.sys_domain", "records.project_manager", "records.operational_outlay", "records.investment_class", "records.resource_planned_cost", "records.expense_type", "records.business_service", "records.expected_start", "records.visited_state", "records.opened_at", "records.primary_program", "records.scrum_epic", "records.irr_value", "records.u_user_leader_principal", "records.submitter", "records.u_report_date_l5", "records.u_report_date_l4", "records.software_model", "records.u_hours_month_of_efficiency", "records.business_case", "records.calendar_duration", "records.u_report_date_l3", "records.u_report_date_l2", "records.close_notes", "records.u_report_date_l1", "records.u_report_date_l0", "records.contact_type", "records.u_spend_detail", "records.u_pmo", "records.department", "records.activity_due", "records.approved_end_date", "records.u_product_quality_risk", "records.u_cancellation_type", "records.comments", "records.u_date_l3_original", "records.capital_outlay", "records.due_date", "records.sys_mod_count", "records.score_size", "records.u_total_fte", "records.barriers", "records.demand_manager", "records.category", "records.u_total_gains"}),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"records Expandido1",{{"records.parent", type text}, {"records.close_demand", type text}, {"records.u_num_sipep", type text}, {"records.watch_list", type text}, {"records.other_costs", Int64.Type}, {"records.u_annual_cash_flow_gain", Int64.Type}, {"records.u_one_time_earning", Int64.Type}, {"records.sys_updated_on", type datetime}, {"records.u_annual_fixed_cost_gain", Int64.Type}, {"records.skills", type any}, {"records.score", Int64.Type}, {"records.u_total_fte_own", Int64.Type}, {"records.u_cancellation_reason", type text}, {"records.related_records", type any}, {"records.u_downgrade_reason_l1", type text}, {"records.labor_costs", Int64.Type}, {"records.u_downgrade_reason_l2", type any}, {"records.u_downgrade_reason_l3", type any}, {"records.u_participants_emails", type text}, {"records.state", Int64.Type}, {"records.u_downgrade_reason_l4", type any}, {"records.sys_created_by", type text}, {"records.expected_roi", Int64.Type}, {"records.goals", type text}, {"records.knowledge", type logical}, {"records.u_downgrade_reason_l0", type text}, {"records.financial_benefit_demand_currency", type text}, {"records.u_risk_description", type text}, {"records.impact", Int64.Type}, {"records.u_training_need", type logical}, {"records.active", type logical}, {"records.demand", type text}, {"records.net_present_value_demand_currency", type text}, {"records.u_kmm_stage", type any}, {"records.u_vice_presidency", type text}, {"records.investment_type", type any}, {"records.group_list", type any}, {"records.size", type text}, {"records.u_benefits", type text}, {"records.u_board_of_directors", type text}, {"records.financial_return", Int64.Type}, {"records.total_costs", Int64.Type}, {"records.score_risk", Int64.Type}, {"records.u_user_leader", type text}, {"records.u_weekly_progress", type text}, {"records.correlation_display", type any}, {"records.u_kpi_detailing", type text}, {"records.service_offering", type any}, {"records.follow_up", type any}, {"records.in_scope", type text}, {"records.u_restrictive_factors", type text}, {"records.u_approval_needed", type logical}, {"records.u_environmental_risk", type text}, {"records.u_implementation_assumptions", type text}, {"records.business_applications", type any}, {"records.u_support_required", type text}, {"records.u_facility_downtime_risk", type text}, {"records.u_cancellation_date", type datetime}, {"records.u_user_leader_history", type text}, {"records.comments_and_work_notes", type any}, {"records.resource_allocated_cost", Int64.Type}, {"records.risk_of_performing", type any}, {"records.u_cancellation_user", type text}, {"records.stage", type text}, {"records.escalation", Int64.Type}, {"records.demand_actual_cost", Int64.Type}, {"records.correlation_id", type any}, {"records.u_ease_of_implementation", type text}, {"records.u_phase", Int64.Type}, {"records.made_sla", type logical}, {"records.scrum_story", type any}, {"records.u_one_time_detail", type any}, {"records.project", type any}, {"records.strategic_objectives", type text}, {"records.enhancement", type any}, {"records.u_date_l4_original", type date}, {"records.capital_budget", Int64.Type}, {"records.user_input", type any}, {"records.sys_created_on", type datetime}, {"records.expected_risk", type text}, {"records.route_reason", type any}, {"records.closed_at", type any}, {"records.time_worked", type any}, {"records.u_demand_stage", Int64.Type}, {"records.npv_value", Int64.Type}, {"records.work_end", type any}, {"records.u_date_l5_original", type date}, {"records.work_notes", type any}, {"records.u_need_for_detailed_risk_analysis", type logical}, {"records.u_department", type text}, {"records.u_next_steps", type text}, {"records.assignment_group", type any}, {"records.u_involved_areas", type text}, {"records.idea", type text}, {"records.description", type text}, {"records.capital_expense_demand_currency", type text}, {"records.risk_of_not_performing", type any}, {"records.sys_id", type text}, {"records.u_number_value_plan", Int64.Type}, {"records.urgency", Int64.Type}, {"records.company", type any}, {"records.rate_model", type any}, {"records.u_current_status", type text}, {"records.u_color_status", type text}, {"records.approved_start_date", type date}, {"records.u_digital_transformation_check", type logical}, {"records.enablers", type text}, {"records.approval", type text}, {"records.model_id", type any}, {"records.improvement", type any}, {"records.sys_tags", type any}, {"records.u_total_fte_third", Int64.Type}, {"records.u_downgrade_user_l4", type any}, {"records.u_downgrade_user_l0", type any}, {"records.u_downgrade_user_l1", type any}, {"records.location", type any}, {"records.u_downgrade_user_l2", type any}, {"records.assessment_required", type logical}, {"records.u_downgrade_user_l3", type any}, {"records.u_need_for_economic_feasibility", type logical}, {"records.project_currency", type text}, {"records.upon_reject", type text}, {"records.type", type text}, {"records.discount_rate", Int64.Type}, {"records.approval_history", type any}, {"records.number", type text}, {"records.defect", type any}, {"records.u_occupational_safety_risk", type text}, {"records.financial_return_demand_currency", type text}, {"records.u_area", type text}, {"records.collaborators", type any}, {"records.order", type any}, {"records.__status", type text}, {"records.goal", type any}, {"records.cmdb_ci", type any}, {"records.contract", type any}, {"records.work_notes_list", type any}, {"records.priority", Int64.Type}, {"records.sys_domain_path", type text}, {"records.business_unit", type any}, {"records.u_next_phase_date", type date}, {"records.business_duration", type any}, {"records.requested_by", type date}, {"records.u_main_results", type text}, {"records.score_value", Int64.Type}, {"records.score_cost", Int64.Type}, {"records.universal_request", type any}, {"records.business_capabilities", type any}, {"records.total_planned_cost_demand_currency", type text}, {"records.short_description", type text}, {"records.operating_expense_demand_currency", type text}, {"records.work_start", type any}, {"records.actual_cost_demand_currency", type text}, {"records.u_annual_revenue_gain", Int64.Type}, {"records.additional_assignee_list", type any}, {"records.sys_class_name", type text}, {"records.closed_by", type any}, {"records.calculation_type", type text}, {"records.capital_budget_demand_currency", type text}, {"records.score_strategic_allignment", Int64.Type}, {"records.u_annual_fixed_avoided_cost", Int64.Type}, {"records.u_main_technology_associated", type text}, {"records.u_last_status_update", type datetime}, {"records.operational_budget", Int64.Type}, {"records.reassignment_count", Int64.Type}, {"records.assigned_to", type text}, {"records.start_date", type date}, {"records.demand_actual_effort", type datetime}, {"records.u_net_gain_value", Int64.Type}, {"records.u_annual_variable_cost_gain", Int64.Type}, {"records.sla_due", type any}, {"records.change", type any}, {"records.demand_currency", type text}, {"records.upon_approval", type text}, {"records.u_annual_variable_avoided_cost", Int64.Type}, {"records.impacted_business_units", type any}, {"records.financial_benefit", Int64.Type}, {"records.u_fte_check", type logical}, {"records.submitted_date", type any}, {"records.u_division", type text}, {"records.operating_budget_demand_currency", type text}, {"records.u_confidential", type logical}, {"records.out_of_scope", type text}, {"records.assumptions", type text}, {"records.task_effective_number", type text}, {"records.u_previous_state", type text}, {"records.sys_updated_by", type text}, {"records.opened_by", type text}, {"records.portfolio", type text}, {"records.u_reducao_co2", Int64.Type}, {"records.sys_domain", type text}, {"records.project_manager", type any}, {"records.operational_outlay", Int64.Type}, {"records.investment_class", type any}, {"records.resource_planned_cost", Int64.Type}, {"records.expense_type", type text}, {"records.business_service", type any}, {"records.expected_start", type any}, {"records.visited_state", Int64.Type}, {"records.opened_at", type datetime}, {"records.primary_program", type text}, {"records.scrum_epic", type any}, {"records.irr_value", type any}, {"records.u_user_leader_principal", type text}, {"records.submitter", type text}, {"records.u_report_date_l5", type date}, {"records.u_report_date_l4", type date}, {"records.software_model", type any}, {"records.u_hours_month_of_efficiency", Int64.Type}, {"records.business_case", type text}, {"records.calendar_duration", type any}, {"records.u_report_date_l3", type date}, {"records.u_report_date_l2", type date}, {"records.close_notes", type any}, {"records.u_report_date_l1", type date}, {"records.u_report_date_l0", type date}, {"records.contact_type", type any}, {"records.u_spend_detail", type text}, {"records.u_pmo", type text}, {"records.department", type text}, {"records.activity_due", type any}, {"records.approved_end_date", type any}, {"records.u_product_quality_risk", type text}, {"records.u_cancellation_type", type text}, {"records.comments", type any}, {"records.u_date_l3_original", type date}, {"records.capital_outlay", Int64.Type}, {"records.due_date", type datetime}, {"records.sys_mod_count", Int64.Type}, {"records.score_size", Int64.Type}, {"records.u_total_fte", Int64.Type}, {"records.barriers", type text}, {"records.demand_manager", type any}, {"records.category", type text}, {"records.u_total_gains", Int64.Type}}),
				    #"Outras Colunas Removidas" = Table.SelectColumns(#"Tipo Alterado",{"records.sys_id", "records.number"}),
				    #"Colunas Reordenadas" = Table.ReorderColumns(#"Outras Colunas Removidas",{"records.number", "records.sys_id"}),
				    #"Colunas Renomeadas" = Table.RenameColumns(#"Colunas Reordenadas",{{"records.number", "Demanda #"}, {"records.sys_id", "Sys_id"}}),
				    #"Personalização Adicionada" = Table.AddColumn(#"Colunas Renomeadas", "URL Demanda", each "https://arcelorbr.service-now.com/tsp3_demand.do?sys_id=" & [Sys_id]),
				    #"Duplicatas Removidas" = Table.Distinct(#"Personalização Adicionada", {"Demanda #"})
				in
				    #"Duplicatas Removidas"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

