table dURL_Projeto
	lineageTag: 8f5fa2f6-2abd-4a6d-8f5f-eeaf0f858ebf

	column Sys_Id
		dataType: string
		lineageTag: 33cc2102-1d40-4746-84cc-809585cf0a5b
		summarizeBy: none
		sourceColumn: Sys_Id

		annotation SummarizationSetBy = Automatic

	column 'Projeto #'
		dataType: string
		lineageTag: 9d17348b-a652-40bd-b9da-07bdc1a34543
		summarizeBy: none
		sourceColumn: Projeto #

		annotation SummarizationSetBy = Automatic

	column 'URL Projeto'
		dataType: string
		lineageTag: c726d272-d2bd-45a1-87c9-bd6ace7f2adb
		dataCategory: WebUrl
		summarizeBy: none
		sourceColumn: URL Projeto

		annotation SummarizationSetBy = Automatic

	column 'URL Status Report'
		dataType: string
		lineageTag: ede45337-93d6-4277-a280-ef052c52fad8
		dataCategory: WebUrl
		summarizeBy: none
		sourceColumn: URL Status Report

		annotation SummarizationSetBy = Automatic

	partition dURL_Projeto = m
		mode: import
		queryGroup: Main
		source =
				let
				    Fonte = Json.Document(Web.Contents("https://arcelormittal.sharepoint.com/sites/CDM-CMT/Shared%20Documents/CMT/00%20-%20Atua%C3%A7%C3%A3o%20CMT/03.%20PBI/dURL_Projeto.json")),
				    #"Convertido para Tabela" = Table.FromRecords({Fonte}),
				    #"records Expandido" = Table.ExpandListColumn(#"Convertido para Tabela", "records"),
				    #"records Expandido1" = Table.ExpandRecordColumn(#"records Expandido", "records", {"parent", "estimate_to_completion_project_currency", "opex_forecast_cost", "watch_list", "phase_type", "sys_updated_on", "skills", "score", "top_program", "capex_cost", "state", "sys_created_by", "goals", "knowledge", "impact", "key_milestone", "active", "opex_estimate_to_completion_project_currency", "demand", "version", "u_kmm_stage", "investment_type", "group_list", "capex_estimate_to_completion", "override_status", "score_risk", "time_component_from_planned", "backlog_definition", "end_date", "correlation_display", "top_task", "resource_assignee", "service_offering", "follow_up", "in_scope", "execution_type", "business_applications", "show_on_program_status_report", "sub_tree_root", "comments_and_work_notes", "estimate_to_completion", "remaining_duration", "capex_forecast_cost_project_currency", "resource_allocated_cost", "risk_of_performing", "project_schedule_date_format", "allow_dates_outside_schedule", "escalation", "correlation_id", "risk_cost", "forecast_cost_project_currency", "made_sla", "strategic_objectives", "wbs_order", "work_effort", "user_input", "sys_created_on", "route_reason", "start_date_derived_from", "project_type", "update_score_on_value_change", "budget_cost_project_currency", "closed_at", "opex_forecast_cost_project_currency", "time_worked", "opex_cost_project_currency", "npv_value", "work_end", "work_notes", "benefits", "work_cost", "assignment_group", "description", "effort", "risk_of_not_performing", "title", "update_actual_effort_from_time_card", "duration", "sys_id", "marked_for_delete", "urgency", "constraint_date", "cost_project_currency", "company", "end", "rate_model", "approved_start_date", "planned_return_project_currency", "enablers", "approval", "start", "model_id", "sys_tags", "html_description", "percent_complete", "schedule", "location", "risk", "shadow", "project_currency", "group_resource_assignee", "actual_cost_project_currency", "auto_save", "wbs", "upon_reject", "status_report_currency", "forecast_cost", "discount_rate", "time_card_preference", "approval_history", "rollup", "number", "schedule_start_date", "capex_forecast_cost", "opex_estimate_to_completion", "order", "__status", "phase", "work_duration", "goal", "budget_cost", "cmdb_ci", "dependency", "contract", "remaining_effort", "work_notes_list", "capex_cost_project_currency", "priority", "sys_domain_path", "business_unit", "business_duration", "score_value", "critical_path", "status", "universal_request", "business_capabilities", "short_description", "work_start", "actual_benefit_project_currency", "time_constraint", "additional_assignee_list", "sys_class_name", "closed_by", "top_portfolio", "calculation_type", "capex_estimate_to_completion_project_currency", "reassignment_count", "schedule_end_date", "assigned_to", "start_date", "mpp_task_id", "sla_due", "attr_based_planning", "has_conflict", "upon_approval", "impacted_business_units", "out_of_scope", "assumptions", "task_effective_number", "sys_updated_by", "opened_by", "sys_domain", "project_manager", "investment_class", "resource_planned_cost", "orig_sys_id", "planned_benefit_project_currency", "expense_type", "level", "business_service", "relation_applied", "expected_start", "npv_project_currency", "actual_benefits", "opened_at", "primary_program", "resources_from_resource_plan", "task", "run_calc_brs", "irr_value", "time_card_at_top_task", "orig_top_task_id", "software_model", "business_case", "calendar_duration", "end_date_derived_from", "roi", "close_notes", "contact_type", "department", "value", "activity_due", "approved_end_date", "primary_portfolio", "comments", "cost", "due_date", "sys_mod_count", "score_size", "opex_cost", "time_zone", "barriers", "milestone"}, {"records.parent", "records.estimate_to_completion_project_currency", "records.opex_forecast_cost", "records.watch_list", "records.phase_type", "records.sys_updated_on", "records.skills", "records.score", "records.top_program", "records.capex_cost", "records.state", "records.sys_created_by", "records.goals", "records.knowledge", "records.impact", "records.key_milestone", "records.active", "records.opex_estimate_to_completion_project_currency", "records.demand", "records.version", "records.u_kmm_stage", "records.investment_type", "records.group_list", "records.capex_estimate_to_completion", "records.override_status", "records.score_risk", "records.time_component_from_planned", "records.backlog_definition", "records.end_date", "records.correlation_display", "records.top_task", "records.resource_assignee", "records.service_offering", "records.follow_up", "records.in_scope", "records.execution_type", "records.business_applications", "records.show_on_program_status_report", "records.sub_tree_root", "records.comments_and_work_notes", "records.estimate_to_completion", "records.remaining_duration", "records.capex_forecast_cost_project_currency", "records.resource_allocated_cost", "records.risk_of_performing", "records.project_schedule_date_format", "records.allow_dates_outside_schedule", "records.escalation", "records.correlation_id", "records.risk_cost", "records.forecast_cost_project_currency", "records.made_sla", "records.strategic_objectives", "records.wbs_order", "records.work_effort", "records.user_input", "records.sys_created_on", "records.route_reason", "records.start_date_derived_from", "records.project_type", "records.update_score_on_value_change", "records.budget_cost_project_currency", "records.closed_at", "records.opex_forecast_cost_project_currency", "records.time_worked", "records.opex_cost_project_currency", "records.npv_value", "records.work_end", "records.work_notes", "records.benefits", "records.work_cost", "records.assignment_group", "records.description", "records.effort", "records.risk_of_not_performing", "records.title", "records.update_actual_effort_from_time_card", "records.duration", "records.sys_id", "records.marked_for_delete", "records.urgency", "records.constraint_date", "records.cost_project_currency", "records.company", "records.end", "records.rate_model", "records.approved_start_date", "records.planned_return_project_currency", "records.enablers", "records.approval", "records.start", "records.model_id", "records.sys_tags", "records.html_description", "records.percent_complete", "records.schedule", "records.location", "records.risk", "records.shadow", "records.project_currency", "records.group_resource_assignee", "records.actual_cost_project_currency", "records.auto_save", "records.wbs", "records.upon_reject", "records.status_report_currency", "records.forecast_cost", "records.discount_rate", "records.time_card_preference", "records.approval_history", "records.rollup", "records.number", "records.schedule_start_date", "records.capex_forecast_cost", "records.opex_estimate_to_completion", "records.order", "records.__status", "records.phase", "records.work_duration", "records.goal", "records.budget_cost", "records.cmdb_ci", "records.dependency", "records.contract", "records.remaining_effort", "records.work_notes_list", "records.capex_cost_project_currency", "records.priority", "records.sys_domain_path", "records.business_unit", "records.business_duration", "records.score_value", "records.critical_path", "records.status", "records.universal_request", "records.business_capabilities", "records.short_description", "records.work_start", "records.actual_benefit_project_currency", "records.time_constraint", "records.additional_assignee_list", "records.sys_class_name", "records.closed_by", "records.top_portfolio", "records.calculation_type", "records.capex_estimate_to_completion_project_currency", "records.reassignment_count", "records.schedule_end_date", "records.assigned_to", "records.start_date", "records.mpp_task_id", "records.sla_due", "records.attr_based_planning", "records.has_conflict", "records.upon_approval", "records.impacted_business_units", "records.out_of_scope", "records.assumptions", "records.task_effective_number", "records.sys_updated_by", "records.opened_by", "records.sys_domain", "records.project_manager", "records.investment_class", "records.resource_planned_cost", "records.orig_sys_id", "records.planned_benefit_project_currency", "records.expense_type", "records.level", "records.business_service", "records.relation_applied", "records.expected_start", "records.npv_project_currency", "records.actual_benefits", "records.opened_at", "records.primary_program", "records.resources_from_resource_plan", "records.task", "records.run_calc_brs", "records.irr_value", "records.time_card_at_top_task", "records.orig_top_task_id", "records.software_model", "records.business_case", "records.calendar_duration", "records.end_date_derived_from", "records.roi", "records.close_notes", "records.contact_type", "records.department", "records.value", "records.activity_due", "records.approved_end_date", "records.primary_portfolio", "records.comments", "records.cost", "records.due_date", "records.sys_mod_count", "records.score_size", "records.opex_cost", "records.time_zone", "records.barriers", "records.milestone"}),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"records Expandido1",{{"records.parent", type text}, {"records.estimate_to_completion_project_currency", type text}, {"records.opex_forecast_cost", Int64.Type}, {"records.watch_list", type any}, {"records.phase_type", type text}, {"records.sys_updated_on", type datetime}, {"records.skills", type any}, {"records.score", Int64.Type}, {"records.top_program", type text}, {"records.capex_cost", Int64.Type}, {"records.state", Int64.Type}, {"records.sys_created_by", type text}, {"records.goals", type any}, {"records.knowledge", type logical}, {"records.impact", Int64.Type}, {"records.key_milestone", type logical}, {"records.active", type logical}, {"records.opex_estimate_to_completion_project_currency", type text}, {"records.demand", type text}, {"records.version", Int64.Type}, {"records.u_kmm_stage", type any}, {"records.investment_type", type text}, {"records.group_list", type any}, {"records.capex_estimate_to_completion", Int64.Type}, {"records.override_status", type logical}, {"records.score_risk", Int64.Type}, {"records.time_component_from_planned", type logical}, {"records.backlog_definition", type any}, {"records.end_date", type datetime}, {"records.correlation_display", type any}, {"records.top_task", type text}, {"records.resource_assignee", type any}, {"records.service_offering", type any}, {"records.follow_up", type any}, {"records.in_scope", type any}, {"records.execution_type", type text}, {"records.business_applications", type any}, {"records.show_on_program_status_report", type logical}, {"records.sub_tree_root", type text}, {"records.comments_and_work_notes", type any}, {"records.estimate_to_completion", Int64.Type}, {"records.remaining_duration", type any}, {"records.capex_forecast_cost_project_currency", type text}, {"records.resource_allocated_cost", Int64.Type}, {"records.risk_of_performing", type text}, {"records.project_schedule_date_format", type text}, {"records.allow_dates_outside_schedule", type logical}, {"records.escalation", Int64.Type}, {"records.correlation_id", type any}, {"records.risk_cost", Int64.Type}, {"records.forecast_cost_project_currency", type text}, {"records.made_sla", type logical}, {"records.strategic_objectives", type any}, {"records.wbs_order", Int64.Type}, {"records.work_effort", type datetime}, {"records.user_input", type any}, {"records.sys_created_on", type datetime}, {"records.route_reason", type any}, {"records.start_date_derived_from", type any}, {"records.project_type", type text}, {"records.update_score_on_value_change", type text}, {"records.budget_cost_project_currency", type text}, {"records.closed_at", type datetime}, {"records.opex_forecast_cost_project_currency", type text}, {"records.time_worked", type any}, {"records.opex_cost_project_currency", type text}, {"records.npv_value", Int64.Type}, {"records.work_end", type datetime}, {"records.work_notes", type any}, {"records.benefits", Int64.Type}, {"records.work_cost", Int64.Type}, {"records.assignment_group", type text}, {"records.description", type text}, {"records.effort", type datetime}, {"records.risk_of_not_performing", type text}, {"records.title", type any}, {"records.update_actual_effort_from_time_card", type text}, {"records.duration", type datetime}, {"records.sys_id", type text}, {"records.marked_for_delete", type logical}, {"records.urgency", Int64.Type}, {"records.constraint_date", type datetime}, {"records.cost_project_currency", type text}, {"records.company", type any}, {"records.end", type date}, {"records.rate_model", type any}, {"records.approved_start_date", type datetime}, {"records.planned_return_project_currency", type text}, {"records.enablers", type any}, {"records.approval", type text}, {"records.start", type date}, {"records.model_id", type any}, {"records.sys_tags", type any}, {"records.html_description", type any}, {"records.percent_complete", Int64.Type}, {"records.schedule", type text}, {"records.location", type any}, {"records.risk", type text}, {"records.shadow", type logical}, {"records.project_currency", type text}, {"records.group_resource_assignee", type any}, {"records.actual_cost_project_currency", type text}, {"records.auto_save", type logical}, {"records.wbs", Int64.Type}, {"records.upon_reject", type text}, {"records.status_report_currency", type text}, {"records.forecast_cost", Int64.Type}, {"records.discount_rate", Int64.Type}, {"records.time_card_preference", type text}, {"records.approval_history", type any}, {"records.rollup", type logical}, {"records.number", type text}, {"records.schedule_start_date", type datetime}, {"records.capex_forecast_cost", Int64.Type}, {"records.opex_estimate_to_completion", Int64.Type}, {"records.order", type any}, {"records.__status", type text}, {"records.phase", type text}, {"records.work_duration", type datetime}, {"records.goal", type any}, {"records.budget_cost", Int64.Type}, {"records.cmdb_ci", type any}, {"records.dependency", type any}, {"records.contract", type any}, {"records.remaining_effort", type datetime}, {"records.work_notes_list", type any}, {"records.capex_cost_project_currency", type text}, {"records.priority", Int64.Type}, {"records.sys_domain_path", type text}, {"records.business_unit", type text}, {"records.business_duration", type any}, {"records.score_value", Int64.Type}, {"records.critical_path", type logical}, {"records.status", type text}, {"records.universal_request", type any}, {"records.business_capabilities", type any}, {"records.short_description", type text}, {"records.work_start", type datetime}, {"records.actual_benefit_project_currency", type text}, {"records.time_constraint", type text}, {"records.additional_assignee_list", type text}, {"records.sys_class_name", type text}, {"records.closed_by", type text}, {"records.top_portfolio", type text}, {"records.calculation_type", type text}, {"records.capex_estimate_to_completion_project_currency", type text}, {"records.reassignment_count", Int64.Type}, {"records.schedule_end_date", type datetime}, {"records.assigned_to", type text}, {"records.start_date", type datetime}, {"records.mpp_task_id", Int64.Type}, {"records.sla_due", type any}, {"records.attr_based_planning", type logical}, {"records.has_conflict", type logical}, {"records.upon_approval", type text}, {"records.impacted_business_units", type text}, {"records.out_of_scope", type any}, {"records.assumptions", type text}, {"records.task_effective_number", type text}, {"records.sys_updated_by", type text}, {"records.opened_by", type text}, {"records.sys_domain", type text}, {"records.project_manager", type text}, {"records.investment_class", type text}, {"records.resource_planned_cost", Int64.Type}, {"records.orig_sys_id", type any}, {"records.planned_benefit_project_currency", type text}, {"records.expense_type", type text}, {"records.level", Int64.Type}, {"records.business_service", type any}, {"records.relation_applied", type any}, {"records.expected_start", type any}, {"records.npv_project_currency", type text}, {"records.actual_benefits", Int64.Type}, {"records.opened_at", type datetime}, {"records.primary_program", type text}, {"records.resources_from_resource_plan", type logical}, {"records.task", type text}, {"records.run_calc_brs", type logical}, {"records.irr_value", Int64.Type}, {"records.time_card_at_top_task", type logical}, {"records.orig_top_task_id", type any}, {"records.software_model", type any}, {"records.business_case", type text}, {"records.calendar_duration", type any}, {"records.end_date_derived_from", type any}, {"records.roi", Int64.Type}, {"records.close_notes", type any}, {"records.contact_type", type any}, {"records.department", type text}, {"records.value", Int64.Type}, {"records.activity_due", type any}, {"records.approved_end_date", type datetime}, {"records.primary_portfolio", type text}, {"records.comments", type any}, {"records.cost", Int64.Type}, {"records.due_date", type any}, {"records.sys_mod_count", Int64.Type}, {"records.score_size", Int64.Type}, {"records.opex_cost", Int64.Type}, {"records.time_zone", type any}, {"records.barriers", type any}, {"records.milestone", type logical}}),
				    #"Outras Colunas Removidas" = Table.SelectColumns(#"Tipo Alterado",{"records.sys_id", "records.number"}),
				    #"Colunas Renomeadas" = Table.RenameColumns(#"Outras Colunas Removidas",{{"records.number", "Projeto #"}, {"records.sys_id", "Sys_Id"}}),
				    #"Personalização Adicionada" = Table.AddColumn(#"Colunas Renomeadas", "URL Projeto", each "https://arcelorbr.service-now.com/$pmview.do?sysparm_view=planning&sysparm_sub_view=planning_console&sysparm_projid=" & [Sys_Id] & "&sysparm_class_name=tsp3_project&sysparm_entity=project"),
				    #"Personalização Adicionada1" = Table.AddColumn(#"Personalização Adicionada", "URL Status Report", each "https://arcelorbr.service-now.com/$pmview.do?sysparm_view=status_report&sysparm_projid=" & [Sys_Id] & "&sysparm_class_name=tsp3_project&sysparm_entity=project")
				in
				    #"Personalização Adicionada1"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

