table fCapex_Projetos
	lineageTag: a84a2579-f9e6-4bb6-9646-5f5d2bfe2959

	column PEP
		dataType: string
		lineageTag: 51936de7-887a-4c46-95e1-23af8f2842a1
		summarizeBy: none
		sourceColumn: PEP

		annotation SummarizationSetBy = Automatic

	column Projeto
		dataType: string
		lineageTag: 7a7a5d93-29d6-44b1-aa5f-2771fd7a8b7c
		summarizeBy: none
		sourceColumn: Projeto

		annotation SummarizationSetBy = Automatic

	partition fCapex_Projetos = m
		mode: import
		queryGroup: Desembolso
		source =
				let
				    Fonte = Excel.Workbook(Web.Contents("https://arcelormittal.sharepoint.com/sites/ROADMAPDC2021/Shared%20Documents/General/ROADMAP%202025/Comit%C3%AA%20Digital%20-%20Roadmap%20DC%202025.xlsx"), null, true),
				    #"Projetos Capex - 2025_Sheet" = Fonte{[Item="Projetos Capex - 2025",Kind="Sheet"]}[Data],
				    #"Cabeçalhos Promovidos" = Table.PromoteHeaders(#"Projetos Capex - 2025_Sheet", [PromoteAllScalars=true]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Cabeçalhos Promovidos",{{"PEP", type text}, {"Projeto", type text}, {"Budget", type number}, {"Subdescrição", type text}, {"GG", type text}, {"G", type text}, {"CMT", type text}, {"CP", type text}, {"JAN/25#(lf)MRF", Int64.Type}, {"JAN/25#(lf)Realizado", Int64.Type}, {"FEV/25#(lf)MRF", type number}, {"FEV/25#(lf)Realizado", Int64.Type}, {"MAR/25#(lf)MRF", Int64.Type}, {"MAR/25#(lf)Realizado", type number}, {"ABR/25#(lf)MRF", type number}, {"ABR/25#(lf)Realizad", Int64.Type}, {"MAI/25#(lf)MRF", Int64.Type}, {"MAI/25#(lf)Realizado", Int64.Type}, {"JUN/25#(lf)MRF", type number}, {"JUN/25#(lf)Realizado", Int64.Type}, {"JUL/25#(lf)MRF", type number}, {"JUL/25#(lf)Realizado", Int64.Type}, {"AGO/25#(lf)MRF", type number}, {"AGO/25#(lf)Realizado", Int64.Type}, {"SET/25#(lf)MRF", Int64.Type}, {"SET/25#(lf)Realizado", Int64.Type}, {"OUT/25#(lf)MRF", Int64.Type}, {"OUT/25#(lf)Realizado", Int64.Type}, {"NOV/25#(lf)MRF", Int64.Type}, {"NOV/25#(lf)Realizado", Int64.Type}, {"DEZ/25#(lf)MRF", Int64.Type}, {"DEZ/25#(lf)Realizado", Int64.Type}, {"JAN/26#(lf)MRF", Int64.Type}, {"JAN/26#(lf)Realizado", Int64.Type}, {"FEV/26#(lf)MRF", Int64.Type}, {"FEV/26#(lf)Realizado", Int64.Type}, {"MRF FY", type number}, {"Realizado FY", type number}, {"MRF x Orçado", type number}, {"Saldo#(lf)(Real-Orçado)", type number}}),
				    #"Linhas Filtradas" = Table.SelectRows(#"Tipo Alterado", each ([Projeto] <> "Total")),
				    #"Colunas Removidas" = Table.RemoveColumns(#"Linhas Filtradas",{"MRF FY", "Realizado FY", "MRF x Orçado", "Saldo#(lf)(Real-Orçado)"}),
				    #"Colunas Não Dinâmicas" = Table.UnpivotOtherColumns(#"Colunas Removidas", {"PEP", "Projeto", "Budget", "Subdescrição", "GG", "G", "CMT", "CP"}, "Atributo", "Valor"),
				    #"Coluna Condicional Adicionada" = Table.AddColumn(#"Colunas Não Dinâmicas", "Tipo", each if Text.Contains([Atributo], "MRF") then "MRF" else "Realizado"),
				    #"Coluna Condicional Adicionada1" = Table.AddColumn(#"Coluna Condicional Adicionada", "Mês", each if Text.Contains([Atributo], "JAN") then 1 else if Text.Contains([Atributo], "FEV") then 2 else if Text.Contains([Atributo], "MAR") then 3 else if Text.Contains([Atributo], "ABR") then 4 else if Text.Contains([Atributo], "MAI") then 5 else if Text.Contains([Atributo], "JUN") then 6 else if Text.Contains([Atributo], "JUL") then 7 else if Text.Contains([Atributo], "AGO") then 8 else if Text.Contains([Atributo], "SET") then 9 else if Text.Contains([Atributo], "OUT") then 10 else if Text.Contains([Atributo], "NOV") then 11 else if Text.Contains([Atributo], "DEZ") then 12 else 0),
				    #"Colunas Removidas1" = Table.RemoveColumns(#"Coluna Condicional Adicionada1",{"Budget", "Subdescrição", "GG", "G", "CMT", "CP", "Atributo", "Valor", "Tipo", "Mês"}),
				    #"Duplicatas Removidas" = Table.Distinct(#"Colunas Removidas1", {"Projeto"})
				in
				    #"Duplicatas Removidas"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

