table fOpex
	lineageTag: 0f58cf69-340a-4f93-9904-d57edea13e55

	column 'OI / CC'
		dataType: string
		lineageTag: 9a329edd-8f84-4eed-96b9-2c48996b7b70
		summarizeBy: none
		sourceColumn: OI / CC

		annotation SummarizationSetBy = Automatic

	column Projeto
		dataType: string
		lineageTag: 92bd8f9f-6a1c-44cb-81be-48314895fc38
		summarizeBy: none
		sourceColumn: Projeto

		annotation SummarizationSetBy = Automatic

	column Budget
		dataType: double
		lineageTag: a5aa9a62-c358-4808-8387-2f755ef87dab
		summarizeBy: sum
		sourceColumn: Budget

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Portfólio
		dataType: string
		lineageTag: cbee4549-35fc-40c1-96d4-22eda9d39d61
		summarizeBy: none
		sourceColumn: Portfólio

		annotation SummarizationSetBy = Automatic

	column Status
		dataType: string
		lineageTag: 6a295572-281b-4349-a953-a11609888360
		summarizeBy: none
		sourceColumn: Status

		annotation SummarizationSetBy = Automatic

	column GG
		dataType: string
		lineageTag: 8fd246b5-c323-41c7-a999-c7408f8afe70
		summarizeBy: none
		sourceColumn: GG

		annotation SummarizationSetBy = Automatic

	column G
		dataType: string
		lineageTag: 56c68279-db60-4e22-8935-b8779a33cc25
		summarizeBy: none
		sourceColumn: G

		annotation SummarizationSetBy = Automatic

	column CMT
		dataType: string
		lineageTag: 18373e2f-f929-4c48-95fb-208743b38c3c
		summarizeBy: none
		sourceColumn: CMT

		annotation SummarizationSetBy = Automatic

	column TI
		dataType: string
		lineageTag: 4587154b-7cf3-41b5-984d-09b4129d121d
		summarizeBy: none
		sourceColumn: TI

		annotation SummarizationSetBy = Automatic

	column Atributo
		dataType: string
		lineageTag: 7037dead-fe9a-4378-8994-1e6f83e6d03f
		summarizeBy: none
		sourceColumn: Atributo

		annotation SummarizationSetBy = Automatic

	column Valor
		dataType: double
		lineageTag: 62bfa086-bfdf-432f-ae38-5761f5c45512
		summarizeBy: sum
		sourceColumn: Valor

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Tipo
		dataType: string
		lineageTag: 4a850829-4d60-44fe-8423-c68d27634070
		summarizeBy: none
		sourceColumn: Tipo

		annotation SummarizationSetBy = Automatic

	partition fOpex = m
		mode: import
		queryGroup: Desembolso\Opex
		source =
				let
				    Fonte = Excel.Workbook(Web.Contents("https://arcelormittal.sharepoint.com/sites/ROADMAPDC2021/Shared%20Documents/General/ROADMAP%202025/Comit%C3%AA%20Digital%20-%20Roadmap%20DC%202025.xlsx"), null, true),
				    #"Projetos Opex - 2025_Sheet" = Fonte{[Item="Projetos Opex - 2025",Kind="Sheet"]}[Data],
				    #"Cabeçalhos Promovidos1" = Table.PromoteHeaders(#"Projetos Opex - 2025_Sheet", [PromoteAllScalars=true]),
				    #"Tipo Alterado1" = Table.TransformColumnTypes(#"Cabeçalhos Promovidos1",{{"OI / CC", type text}, {"Projeto", type text}, {"Budget", type number}, {"Portfólio", type text}, {"Status", type text}, {"GG", type text}, {"G", type text}, {"CMT", type text}, {"TI", type text}, {"JAN/25#(lf)MRF", type number}, {"JAN/25#(lf)Realizado", type number}, {"FEV/25#(lf)MRF", type number}, {"FEV/25#(lf)Realizado", type number}, {"MAR/25#(lf)MRF", type number}, {"MAR/25#(lf)Realizado", type number}, {"ABR/25#(lf)MRF", type number}, {"ABR/25#(lf)Realizad", Int64.Type}, {"MAI/25#(lf)MRF", type number}, {"MAI/25#(lf)Realizado", Int64.Type}, {"JUN/25#(lf)MRF", type number}, {"JUN/25#(lf)Realizado", Int64.Type}, {"JUL/25#(lf)MRF", type number}, {"JUL/25#(lf)Realizado", Int64.Type}, {"AGO/25#(lf)MRF", type number}, {"AGO/25#(lf)Realizado", Int64.Type}, {"SET/25#(lf)MRF", type number}, {"SET/25#(lf)Realizado", Int64.Type}, {"OUT/25#(lf)MRF", type number}, {"OUT/25#(lf)Realizado", Int64.Type}, {"NOV/25#(lf)MRF", type number}, {"NOV/25#(lf)Realizado", Int64.Type}, {"DEZ/25#(lf)MRF", type number}, {"DEZ/25#(lf)Realizado", Int64.Type}, {"JAN/26#(lf)MRF", Int64.Type}, {"JAN/26#(lf)Realizado", Int64.Type}, {"FEV/26#(lf)MRF", Int64.Type}, {"FEV/26#(lf)Realizado", Int64.Type}, {"MRF FY", type number}, {"Realizado FY", type number}, {"MRF x Orçado", type number}, {"Saldo#(lf)(Real-Orçado)", type number}, {"Demanda Casulo", type text}, {"Projeto Casulo", type text}, {"Demanda T4", type text}}),
				    #"Colunas Removidas" = Table.RemoveColumns(#"Tipo Alterado1",{"MRF FY", "Realizado FY", "MRF x Orçado", "Saldo#(lf)(Real-Orçado)", "Demanda Casulo", "Projeto Casulo", "Demanda T4"}),
				    #"Linhas Filtradas" = Table.SelectRows(#"Colunas Removidas", each ([Projeto] <> "Total")),
				    #"Colunas Não Dinâmicas" = Table.UnpivotOtherColumns(#"Linhas Filtradas", {"OI / CC", "Projeto", "Budget", "Portfólio", "Status", "GG", "G", "CMT", "TI"}, "Atributo", "Valor"),
				    #"Coluna Condicional Adicionada" = Table.AddColumn(#"Colunas Não Dinâmicas", "Tipo", each if Text.Contains([Atributo], "MRF") then "MRF" else "Realizado")
				in
				    #"Coluna Condicional Adicionada"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

