table fOpex_Resumo
	lineageTag: 308be4ca-e1a6-4693-8f66-d600e56cd701

	column 'OI / CC'
		dataType: string
		lineageTag: 4acbd1f3-6835-4fec-9bb0-78c803d57472
		summarizeBy: none
		sourceColumn: OI / CC

		annotation SummarizationSetBy = Automatic

	column Projeto
		dataType: string
		lineageTag: 1498e6c3-a10d-46a7-9186-c6d941d36ed9
		summarizeBy: none
		sourceColumn: Projeto

		annotation SummarizationSetBy = Automatic

	column Budget
		dataType: double
		lineageTag: ce9491bc-351d-48c3-8082-d6d0e2b791b2
		summarizeBy: none
		sourceColumn: Budget

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Portfólio
		dataType: string
		lineageTag: d1298745-97c8-4e18-beca-bae13d62f206
		summarizeBy: none
		sourceColumn: Portfólio

		annotation SummarizationSetBy = Automatic

	column Status
		dataType: string
		lineageTag: 97884ad1-0717-4041-8c9a-881c99e9aa21
		summarizeBy: none
		sourceColumn: Status

		annotation SummarizationSetBy = Automatic

	column GG
		dataType: string
		lineageTag: ff98088d-9e3c-4475-ad55-b5b4ea16e408
		summarizeBy: none
		sourceColumn: GG

		annotation SummarizationSetBy = Automatic

	column G
		dataType: string
		lineageTag: 4c6bdeb9-ec97-44c7-aba9-fd0e6483b8c1
		summarizeBy: none
		sourceColumn: G

		annotation SummarizationSetBy = Automatic

	column CMT
		dataType: string
		lineageTag: ca8850b2-c4a2-4a35-9d87-6d71590d7af9
		summarizeBy: none
		sourceColumn: CMT

		annotation SummarizationSetBy = Automatic

	column TI
		dataType: string
		lineageTag: 81d3f639-b948-4811-b304-a7ac01010adc
		summarizeBy: none
		sourceColumn: TI

		annotation SummarizationSetBy = Automatic

	partition fOpex_Resumo = m
		mode: import
		queryGroup: Desembolso\Opex
		source =
				let
				    Fonte = Excel.Workbook(Web.Contents("https://arcelormittal.sharepoint.com/sites/ROADMAPDC2021/Shared%20Documents/General/ROADMAP%202025/Comit%C3%AA%20Digital%20-%20Roadmap%20DC%202025.xlsx"), null, true),
				    #"Projetos Opex - 2025_Sheet" = Fonte{[Item="Projetos Opex - 2025",Kind="Sheet"]}[Data],
				    #"Cabeçalhos Promovidos1" = Table.PromoteHeaders(#"Projetos Opex - 2025_Sheet", [PromoteAllScalars=true]),
				    #"Tipo Alterado1" = Table.TransformColumnTypes(#"Cabeçalhos Promovidos1",{{"OI / CC", type text}, {"Projeto", type text}, {"Budget", type number}, {"Portfólio", type text}, {"Status", type text}, {"GG", type text}, {"G", type text}, {"CMT", type text}, {"TI", type text}, {"JAN/25#(lf)MRF", type number}, {"JAN/25#(lf)Realizado", type number}, {"FEV/25#(lf)MRF", type number}, {"FEV/25#(lf)Realizado", type number}, {"MAR/25#(lf)MRF", type number}, {"MAR/25#(lf)Realizado", type number}, {"ABR/25#(lf)MRF", type number}, {"ABR/25#(lf)Realizad", Int64.Type}, {"MAI/25#(lf)MRF", type number}, {"MAI/25#(lf)Realizado", Int64.Type}, {"JUN/25#(lf)MRF", type number}, {"JUN/25#(lf)Realizado", Int64.Type}, {"JUL/25#(lf)MRF", type number}, {"JUL/25#(lf)Realizado", Int64.Type}, {"AGO/25#(lf)MRF", type number}, {"AGO/25#(lf)Realizado", Int64.Type}, {"SET/25#(lf)MRF", type number}, {"SET/25#(lf)Realizado", Int64.Type}, {"OUT/25#(lf)MRF", type number}, {"OUT/25#(lf)Realizado", Int64.Type}, {"NOV/25#(lf)MRF", type number}, {"NOV/25#(lf)Realizado", Int64.Type}, {"DEZ/25#(lf)MRF", type number}, {"DEZ/25#(lf)Realizado", Int64.Type}, {"JAN/26#(lf)MRF", Int64.Type}, {"JAN/26#(lf)Realizado", Int64.Type}, {"FEV/26#(lf)MRF", Int64.Type}, {"FEV/26#(lf)Realizado", Int64.Type}, {"MRF FY", type number}, {"Realizado FY", type number}, {"MRF x Orçado", type number}, {"Saldo#(lf)(Real-Orçado)", type number}, {"Demanda Casulo", type text}, {"Projeto Casulo", type text}, {"Demanda T4", type text}}),
				    #"Colunas Removidas" = Table.RemoveColumns(#"Tipo Alterado1",{"MRF FY", "Realizado FY", "MRF x Orçado", "Saldo#(lf)(Real-Orçado)", "Demanda Casulo", "Projeto Casulo", "Demanda T4", "JAN/25#(lf)MRF", "JAN/25#(lf)Realizado", "FEV/25#(lf)MRF", "FEV/25#(lf)Realizado", "MAR/25#(lf)MRF", "MAR/25#(lf)Realizado", "ABR/25#(lf)MRF", "ABR/25#(lf)Realizad", "MAI/25#(lf)MRF", "MAI/25#(lf)Realizado", "JUN/25#(lf)MRF", "JUN/25#(lf)Realizado", "JUL/25#(lf)MRF", "JUL/25#(lf)Realizado", "AGO/25#(lf)MRF", "AGO/25#(lf)Realizado", "SET/25#(lf)MRF", "SET/25#(lf)Realizado", "OUT/25#(lf)MRF", "OUT/25#(lf)Realizado", "NOV/25#(lf)MRF", "NOV/25#(lf)Realizado", "DEZ/25#(lf)MRF", "DEZ/25#(lf)Realizado", "JAN/26#(lf)MRF", "JAN/26#(lf)Realizado", "FEV/26#(lf)MRF", "FEV/26#(lf)Realizado"}),
				    #"Linhas Filtradas" = Table.SelectRows(#"Colunas Removidas", each ([Projeto] <> "Total") and ([#"OI / CC"] <> "-" and [#"OI / CC"] <> "CCD" and [#"OI / CC"] <> "INO.VC" and [#"OI / CC"] <> "Opex Área"))
				in
				    #"Linhas Filtradas"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

