table GIT_Participações
	lineageTag: 49f10c47-7e30-4ba5-99db-9b5013f917d0

	column Colaborador
		dataType: string
		lineageTag: 804c5d32-16f6-46e2-8e5d-6813d8d1e36c
		summarizeBy: none
		sourceColumn: Colaborador

		annotation SummarizationSetBy = Automatic

	column 'Data Inicial'
		dataType: dateTime
		formatString: Short Date
		lineageTag: 74f0f0aa-a363-44d5-baa2-788a13acfcdf
		summarizeBy: none
		sourceColumn: Data Inicial

		variation Variation
			isDefault
			relationship: d6b77549-a7f2-4c9e-8bc3-8c284e5ccafb
			defaultHierarchy: LocalDateTable_7b5a61db-89c9-4b11-a6b4-a2dfb2322ee9.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Data Final'
		dataType: dateTime
		formatString: Short Date
		lineageTag: 1e2f1438-fae4-4412-b854-7eb106b39a8c
		summarizeBy: none
		sourceColumn: Data Final

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Participação
		dataType: string
		lineageTag: 21ea8671-a45b-4483-a475-50313c083d68
		summarizeBy: none
		sourceColumn: Participação

		annotation SummarizationSetBy = Automatic

	column Empresa
		dataType: string
		lineageTag: c7bd22cb-d71f-42c5-9a0c-bc45aaa70e1a
		summarizeBy: none
		sourceColumn: Empresa

		annotation SummarizationSetBy = Automatic

	column Tema
		dataType: string
		lineageTag: 7b6ce677-e817-43f5-9908-98a8eef59da4
		summarizeBy: none
		sourceColumn: Tema

		annotation SummarizationSetBy = Automatic

	column Local
		dataType: string
		lineageTag: ee21ca18-539f-4ec1-b6e7-dcacb316e942
		summarizeBy: none
		sourceColumn: Local

		annotation SummarizationSetBy = Automatic

	column Status
		dataType: string
		lineageTag: cfc60a26-a6ad-4432-ac43-749c796c7088
		summarizeBy: none
		sourceColumn: Status

		annotation SummarizationSetBy = Automatic

	partition GIT_Participações = m
		mode: import
		queryGroup: GIT
		source =
				let
				    Fonte = SharePoint.Files("https://arcelormittal.sharepoint.com/sites/CDM-CMT/", [ApiVersion = 15]),
				    #"Linhas Classificadas" = Table.Sort(Fonte,{{"Name", Order.Ascending}}),
				    #"Fonte de Dados GIT CMT xlsx_https://arcelormittal sharepoint com/sites/CDM-CMT/Shared Documents/CMT/11 - GIT CMT/" = #"Linhas Classificadas"{[Name="Fonte de Dados GIT CMT.xlsx",#"Folder Path"="https://arcelormittal.sharepoint.com/sites/CDM-CMT/Shared Documents/CMT/11 - GIT CMT/"]}[Content],
				    #"Pasta de Trabalho Importada do Excel" = Excel.Workbook(#"Fonte de Dados GIT CMT xlsx_https://arcelormittal sharepoint com/sites/CDM-CMT/Shared Documents/CMT/11 - GIT CMT/"),
				    #"Participações CMT_Sheet" = #"Pasta de Trabalho Importada do Excel"{[Item="Participações CMT",Kind="Sheet"]}[Data],
				    #"Linhas Superiores Removidas" = Table.Skip(#"Participações CMT_Sheet",1),
				    #"Cabeçalhos Promovidos" = Table.PromoteHeaders(#"Linhas Superiores Removidas", [PromoteAllScalars=true]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Cabeçalhos Promovidos",{{"Colaborador", type text}, {"Data Inicial", type date}, {"Data Final", type date}, {"Participação", type text}, {"Empresa", type text}, {"Tema", type text}, {"Local", type text}, {"Status", type text}}),
				    #"Linhas em Branco Removidas" = Table.SelectRows(#"Tipo Alterado", each not List.IsEmpty(List.RemoveMatchingItems(Record.FieldValues(_), {"", null})))
				in
				    #"Linhas em Branco Removidas"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegação

