table GIT_Treinamentos_Compliance
	lineageTag: 2a56287d-655a-4961-995c-dcc4ddca4596

	column Data
		dataType: dateTime
		formatString: Long Date
		lineageTag: d70952f9-51a8-4238-997a-79487ffd7e1d
		summarizeBy: none
		sourceColumn: Data

		variation Variation
			isDefault
			relationship: 7916e541-bf65-4d96-be84-25c0a8fa365f
			defaultHierarchy: LocalDateTable_231db280-ed32-42d5-928e-13c9540b6332.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Realizado
		dataType: double
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 607131e1-3ecd-4b30-9cf7-96fddf40f2ff
		summarizeBy: sum
		sourceColumn: Realizado

		annotation SummarizationSetBy = Automatic

	column Meta
		dataType: double
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: ec74e8bd-27de-48c0-bbac-9ec353dc8497
		summarizeBy: sum
		sourceColumn: Meta

		annotation SummarizationSetBy = Automatic

	partition GIT_Treinamentos_Compliance = m
		mode: import
		queryGroup: GIT
		source =
				let
				    Fonte = SharePoint.Files("https://arcelormittal.sharepoint.com/sites/CDM-CMT/", [ApiVersion = 15]),
				    #"Linhas Classificadas" = Table.Sort(Fonte,{{"Name", Order.Ascending}}),
				    #"Fonte de Dados GIT CMT xlsx_https://arcelormittal sharepoint com/sites/CDM-CMT/Shared Documents/CMT/11 - GIT CMT/" = #"Linhas Classificadas"{[Name="Fonte de Dados GIT CMT.xlsx",#"Folder Path"="https://arcelormittal.sharepoint.com/sites/CDM-CMT/Shared Documents/CMT/11 - GIT CMT/"]}[Content],
				    #"Pasta de Trabalho Importada do Excel" = Excel.Workbook(#"Fonte de Dados GIT CMT xlsx_https://arcelormittal sharepoint com/sites/CDM-CMT/Shared Documents/CMT/11 - GIT CMT/"),
				    #"Treinamentos de compliance_Sheet" = #"Pasta de Trabalho Importada do Excel"{[Item="Treinamentos de compliance",Kind="Sheet"]}[Data],
				    #"Cabeçalhos Promovidos" = Table.PromoteHeaders(#"Treinamentos de compliance_Sheet", [PromoteAllScalars=true]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Cabeçalhos Promovidos",{{"Data", type date}, {"Realizado", Percentage.Type}, {"Meta", Percentage.Type}})
				in
				    #"Tipo Alterado"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegação

